"""empty message

Revision ID: 8def3f25b639
Revises: 78dc1d30b961
Create Date: 2016-12-07 01:14:25.704061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8def3f25b639'
down_revision = '78dc1d30b961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
